import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const certPath = path.join(rootDir, 'certs', 'server-cert.pem');
const keyPath = path.join(rootDir, 'certs', 'server-key.pem');

// Camera access requires a secure origin, so serve over https whenever the
// dev certificate generated by `npm run dev:cert` is present.
const hasCert = fs.existsSync(certPath) && fs.existsSync(keyPath);

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    strictPort: true,
    host: '0.0.0.0',
    allowedHosts: true,
    ...(hasCert
      ? { https: { cert: fs.readFileSync(certPath), key: fs.readFileSync(keyPath) } }
      : {})
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true
  }
});
